name: Video Projector Submission
description: Fill out this form to create a new video projetor entry and pull request.
title: "[New Video Projector]: "
labels: [projector_submission]

body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to make the database better! After creating this issue a PR will automatically be created with all files generated."

  - type: textarea
    id: product_page
    attributes:
      label: "Product Page"
      description: "Please enter the URL of the product page or specification sheet. This is just to keep track on where the data comes from."
      placeholder: "https://www.barco.com/en/product/udx-4k32"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "# Projector information"

  - type: dropdown
    id: vendor
    attributes:
      label: "Vendor"
      description: "Select the proejctor manufacturer"
      options:
        - Barco
        - Christie
        - Panasonic
        - Sony
        - Other
    validations:
      required: true
